// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daeupcfiorrfncaesilv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhZXVwY2Zpb3JyZm5jYWVzaWx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTM0OTMsImV4cCI6MjA3MjkyOTQ5M30.TdHONCFXc4O_sHwUyIlkc8RsHTEXIsr7xLpfPy2YX4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});